services:
  backend:
    container_name: backend-app
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    ports:
      - "4200:80"
    restart: unless-stopped
    # depends_on:
    #   - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
