name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "apps/frontend/**"
      - "consts/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npx nx test frontend --verbose --runInBand

      - name: Deploy to Vercel
        if: success()
        run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"

      - name: Notify Discord
        if: always()
        run: |
          curl -H "Content-Type: application/json" \
            -X POST ${{ secrets.DISCORD_WEBHOOK_URL }} \
            -d '{
              "username": "GitHub Actions",
              "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "embeds": [{
                "title": "🚀 Frontend Deployment",
                "description": "**Status:** `${{ job.status }}`\n**Branch:** `${{ github.ref_name }}`\n**Commit:** `${{ github.sha }}`",
                "color": 5814783
              }]
            }'
